Combine stay history
mclhtay/CS4471 pull request #42
Opened 2022-11-25 03:09 UTC by John-Merritt

admin menu now looks like this:
![image](https://user-images.githubusercontent.com/50186952/203892467-8dc5dbaa-8584-41d8-a1b1-f74ac2f91520.png)

2022-11-25 22:01 UTC, mclhtay requested changes

2022-11-25 22:01 UTC, mclhtay commented on HotelBooking/Views/admin_view.py
> +                    "name": reservation.room_id+", with reservation id: "+str(reservation.reservation_id)+", start on: "+reservation.reservation_checkin_date+", stay for: "+str(reservation.reservatio
This is getting too long. Use a multi-line template string instead. 

i.e., 
```
(f"{reservation.room_id} with reservation id: {...} ..."

f"...."

f"....") 
```

2022-11-25 22:01 UTC, mclhtay commented on HotelBooking/Views/admin_view.py
> +                roomID = answer_list[0].strip()
`room_id`

2022-11-25 22:05 UTC, John-Merritt commented on HotelBooking/Views/admin_view.py
> +                roomID = answer_list[0].strip()
same as above

2022-11-27 22:25 UTC, mclhtay approved these changes

2022-11-27 22:35 UTC, merged